### ISSUE TITLE
Unused wiretrustee-signal volume in docker-compose.yml file

### ISSUE THREAD

**Issue by IsaacTay** [wiretrustee/wiretrustee#117]
Is the signal service suppose to have it's own volume for mounting, or are both management and signal services suppose to share the same mount?

**Comment by braginini** [comment]
Signal is supposed to have it's own volume named wiretrustee-signal.
There was a bug in the docker-compose, I fixed it.
Also, the volume is not actually needed if you run signal without SSL.

**Comment by IsaacTay** [comment]
Ah, I see. I am excited to see where this project will go, thanks for the clarification!
