### ISSUE TITLE
Creating a new key on the app.wiretrustee.com does not show up in the list of keys

### ISSUE THREAD

**Issue by harishpillay** [wiretrustee/wiretrustee#149]
I tried to create a new key (by hitting the "+New Key" in https://app.wiretrustee.com/setup-keys. I provided a name and picked reusable. But the key did not appear in the list of keys.

**Comment by braginini** [comment]
Hey @harishpillay 
Are you still facing the issue?
If so, could you please send us your email address to dev@wiretrustee.com referencing this issue?

Thank you

**Comment by harishpillay** [comment]
@braginini it is now on the list but they are offline. I've just updated it to 0.2.3 and those that were online are (CentOS Stream 8 and Debian 11.1) while the Fedora 35 are still offline.

**Comment by harishpillay** [comment]
I will close this issue. Thanks.
