### ISSUE TITLE
Peer Status Online but not Connected.

### ISSUE THREAD

**Issue by MANKUD** [wiretrustee/wiretrustee#151]
Hello,

I was trying to connect two windows machines and looks like they are shown online in the management dashboard but are not shown as connected is there something that I missed?

Since they are not shown as connected I am not able to get a ping response.

![image](https://user-images.githubusercontent.com/83474708/140477700-bf580e3e-90d1-43f8-869e-68c6a33dc11e.png)

![image](https://user-images.githubusercontent.com/83474708/140483134-8081e2f1-2134-4d25-9ba9-568b11acf04c.png)

**Comment by braginini** [comment]
Thank you for reporting the issue @MANKUD 

We have changed the statuses displayed in the dashboard to avoid confusion.
We have 2 statuses now - [Offline, Online] that indicate whether peers are online and connected to the management service or not.
However, these statuses do not represent the connection status between peers (since the connections are peer-to-peer).

Would you mind sending us the recent output of the client log file? It is located under C:\ProgramData\Wiretrustee folder on Windows.

**Comment by MANKUD** [comment]
Here is the log file
[client.log](https://github.com/wiretrustee/wiretrustee/files/7488762/client.log)
.

**Comment by stickman89** [comment]
This is relating to Windows Firewall... Add Inbound and Outbound rules for Wiretrustee's assigned IP Address range to 'Windows Defender Firewall with Advanced Security' to 'Allow the connection'; atleast untill this is fixed by the dev's here.

![image](https://user-images.githubusercontent.com/10897072/140610912-57ecbdbc-e3e2-4053-acc5-9f6c84bc55b1.png)

**Comment by MANKUD** [comment]
@stickman89 I tried disabling the firewall on both  the peers and tried to ping and it did not help so I think its not issue with firewall.

**Comment by Soneji** [comment]
I'm having the same issue, same client logs

**Comment by Chris3606** [comment]
Same issue, same client logs, trying to connect a Windows 10 to a Linux Mint box.  My exact setup worked fine as of about a week and a half ago.  I completely disabled firewalls on both boxes for the sake of testing, no effect.

**Comment by mlsmaycon** [comment]
Hello @MANKUD @Soneji sorry to hear that you facing these issues. In order to troubleshoot the issue, can you confirm the versions of the clients and could you run the following commands to enable a more verbose log:

```shell
wiretrustee service stop
wiretrustee service uninstall
wiretrustee service install --log-level debug
wiretrustee service start
```

> In Windows you may need to run the powershell as admin and on Linux you need sudo

After that it will be great if you can share the log files.

**Comment by MANKUD** [comment]
> Hello @MANKUD @Soneji sorry to hear that you facing these issues. In order to troubleshoot the issue, can you confirm the versions of the clients and could you run the following commands to enable a more verbose log:
> 
> ```shell
> wiretrustee service stop
> wiretrustee service uninstall
> wiretrustee service install --log-level debug
> wiretrustee service start
> ```
> 
> > In Windows you may need to run the powershell as admin and on Linux you need sudo
> 
> After that it will be great if you can share the log files from at least 2 peers that can't communicate.

Here are the log file after enabling a more verbose log.

[client 2.log](https://github.com/wiretrustee/wiretrustee/files/7504414/client.2.log)

[client 1.log](https://github.com/wiretrustee/wiretrustee/files/7504413/client.1.log)

**Comment by mlsmaycon** [comment]
@MANKUD sorry for the delay in replying. 

Checking client1.log it seems like debug wasn't enabled there. Can you run the commands above for this client too?

**Comment by mlsmaycon** [comment]
@MANKUD we found and fixed an issue with one of our TURN servers, can you test again?

**Comment by Chris3606** [comment]
@mlsmaycon Although I'm not the OP, I did have the same issue and now it's fixed, for what that's worth; hoping the OP can verify as well.

**Comment by mlsmaycon** [comment]
Thank you for the feedback @Chris3606, glad it is working again for you.

**Comment by MANKUD** [comment]
@mlsmaycon I am getting his error on one of the systems that I am trying to add as peer.

![image](https://user-images.githubusercontent.com/83474708/141439733-1a6460ee-6af3-4e28-8c5a-08e12caf4d81.png)

**Comment by MANKUD** [comment]
@mlsmaycon 

I am able to ping now seems like the issue is fixed also let me know how to solve the above-mentioned error.

**Comment by MANKUD** [comment]
@mlsmaycon 
Also, there was an issue on windows on version wiretrustee_installer_0.2.2-beta.1_windows_amd64 the wiretrustee service just stops after a while and does not run and need to be manually started. I am not sure if that issue is fixed on the latest release.

**Comment by braginini** [comment]
> @mlsmaycon Also, there was an issue on windows on version wiretrustee_installer_0.2.2-beta.1_windows_amd64 the wiretrustee service just stops after a while and does not run and need to be manually started. I am not sure if that issue is fixed on the latest release.

Thank you @MANKUD  for mentioning this. Indeed there was an issue, specifically when there were reconnects to the Signal service. It was fixed and the latest version doesn't have this problem anymore
https://github.com/wiretrustee/wiretrustee/releases/tag/v0.2.3

**Comment by braginini** [comment]
> @mlsmaycon I am getting his error on one of the systems that I am trying to add as peer.
> 
> ![image](https://user-images.githubusercontent.com/83474708/141439733-1a6460ee-6af3-4e28-8c5a-08e12caf4d81.png)

Would you mind updating to the latest version? 
We have also increased timeouts while the client tries to connect to the signal and management services.

We might also introduce some simple retry logic there (e.g. up to 3 times). What do you think @MANKUD ?

**Comment by MANKUD** [comment]
@braginini 

it's already updated to the latest release. I tried multiple times to add the peer but I am getting the same error not sure why getting such an error.

![image](https://user-images.githubusercontent.com/83474708/141470889-8efa4f93-4c9b-4d6e-a99b-7bd1bcc2cf29.png)

Simple retry logic sounds promising.

**Comment by MANKUD** [comment]
@braginini 
Are you planning to add an option to create multiple networks where we can have multiple IP ranges for different networks or even the same IP range on the multiple networks and not just the default 100.64.0.x?

**Comment by braginini** [comment]
> @braginini Are you planning to add an option to create multiple networks where we can have multiple IP ranges for different networks or even the same IP range on the multiple networks and not just the default 100.64.0.x?

@MANKUD 
We wanted to address the network split by introducing ACLs. 
Simply put, you'd be able to create groups of peers and they would be able to connect to each other only, not interfering with other groups.

**Comment by braginini** [comment]
> @braginini
> 
> it's already updated to the latest release. I tried multiple times to add the peer but I am getting the same error not sure why getting such an error.
> 
> ![image](https://user-images.githubusercontent.com/83474708/141470889-8efa4f93-4c9b-4d6e-a99b-7bd1bcc2cf29.png)
> 
> Simple retry logic sounds promising.

That is strange
may I ask you to show a client.log?

**Comment by MANKUD** [comment]
> > @braginini Are you planning to add an option to create multiple networks where we can have multiple IP ranges for different networks or even the same IP range on the multiple networks and not just the default 100.64.0.x?
> 
> @MANKUD We wanted to address the network split by introducing ACLs. Simply put, you'd be able to create groups of peers and they would be able to connect to each other only, not interfering with other groups.

@braginini 
Would I be able to use the same IP range in the different group of peers for example use the same default 100.64.0.x for multiple groups and also would there be an option to choose the desired IP range something like 10.0.0.1 or 10.1.1.1 etc instead of 100.64.0.x?

**Comment by MANKUD** [comment]
> > @braginini
> > it's already updated to the latest release. I tried multiple times to add the peer but I am getting the same error not sure why getting such an error.
> > ![image](https://user-images.githubusercontent.com/83474708/141470889-8efa4f93-4c9b-4d6e-a99b-7bd1bcc2cf29.png)
> > Simple retry logic sounds promising.
> 
> That is strange may I ask you to show a client.log?

@braginini 

here is the log file attached. 
[client.log](https://github.com/wiretrustee/wiretrustee/files/7527843/client.log)

**Comment by braginini** [comment]
> > > @braginini
> > > it's already updated to the latest release. I tried multiple times to add the peer but I am getting the same error not sure why getting such an error.
> > > ![image](https://user-images.githubusercontent.com/83474708/141470889-8efa4f93-4c9b-4d6e-a99b-7bd1bcc2cf29.png)
> > > Simple retry logic sounds promising.
> > 
> > 
> > That is strange may I ask you to show a client.log?
> 
> @braginini
> 
> here is the log file attached. [client.log](https://github.com/wiretrustee/wiretrustee/files/7527843/client.log)

@MANKUD could u plz ping  api.wiretrustee.com ? 
also what is the output of ? 
`telnet api.wiretrustee.com 33073`

**Comment by MANKUD** [comment]
> > > > @braginini
> > > > it's already updated to the latest release. I tried multiple times to add the peer but I am getting the same error not sure why getting such an error.
> > > > ![image](https://user-images.githubusercontent.com/83474708/141470889-8efa4f93-4c9b-4d6e-a99b-7bd1bcc2cf29.png)
> > > > Simple retry logic sounds promising.
> > > 
> > > 
> > > That is strange may I ask you to show a client.log?
> > 
> > 
> > @braginini
> > here is the log file attached. [client.log](https://github.com/wiretrustee/wiretrustee/files/7527843/client.log)
> 
> @MANKUD could u plz ping api.wiretrustee.com ? also what is the output of `telnet api.wiretrustee.com 33073` ?

@braginini 

![image](https://user-images.githubusercontent.com/83474708/141478523-9fc1b5a6-eb63-4f93-b05c-d462f5a4def0.png)

![image](https://user-images.githubusercontent.com/83474708/141478541-0cfacd96-479d-41c9-9c0a-2686f54c7b18.png)

**Comment by braginini** [comment]
> > > > > @braginini
> > > > > it's already updated to the latest release. I tried multiple times to add the peer but I am getting the same error not sure why getting such an error.
> > > > > ![image](https://user-images.githubusercontent.com/83474708/141470889-8efa4f93-4c9b-4d6e-a99b-7bd1bcc2cf29.png)
> > > > > Simple retry logic sounds promising.
> > > > 
> > > > 
> > > > That is strange may I ask you to show a client.log?
> > > 
> > > 
> > > @braginini
> > > here is the log file attached. [client.log](https://github.com/wiretrustee/wiretrustee/files/7527843/client.log)
> > 
> > 
> > @MANKUD could u plz ping api.wiretrustee.com ? also what is the output of `telnet api.wiretrustee.com 33073` ?
> 
> @braginini
> 
> ![image](https://user-images.githubusercontent.com/83474708/141478523-9fc1b5a6-eb63-4f93-b05c-d462f5a4def0.png)
> 
> ![image](https://user-images.githubusercontent.com/83474708/141478541-0cfacd96-479d-41c9-9c0a-2686f54c7b18.png)

This is suprasingly strange.

Could you please try running `telnet signal2.wiretrustee.com 10000` to check whether the problem persists also for the Signal service?

P.S. I'm able to successfully establish connection with telnet

**Comment by MANKUD** [comment]
@braginini 

Unfortunately, the connection failed to that too.

![image](https://user-images.githubusercontent.com/83474708/141506021-53e68933-da8e-4435-bac3-3d202bb33b74.png)

**Comment by mlsmaycon** [comment]
@MANKUD It seems like you have either a local network restriction to the services ports. Looking by the logs, it seems that either you moved the client to a new network as it was able to connect to our management system before or something changed in the client itself. 

Can you give us more details regarding its network? if possible, test from another computer in the network as well.

**Comment by MANKUD** [comment]
@mlsmaycon 

Hello the client was not moved to a different network it's in the same network and yes I was able to join the management system before but I had removed the app and now when I am trying again I am not able to join at all and it's giving the error I mentioned above. The network does not have any restrictions as such it's connected to a router with dynamic IP and there is no special firewall as such installed.

**Comment by mlsmaycon** [comment]
@MANKUD did you check from another client in the same network? 

You mentioned that there is no special firewall installed, but did you check with it temporarily disabled and perhaps antivirus too?

**Comment by braginini** [comment]
additionally to what @mlsmaycon  asked, @MANKUD could you please run these commands?

`telnet apitest.wiretrustee.com 33073`
`telnet apitest.wiretrustee.com 33071`

`telnet apitest.wiretrustee.com 80`
`telnet apitest.wiretrustee.com 443`


What is the output?

**Comment by MANKUD** [comment]
@mlsmaycon

Hi unfortunately I do not have access to any other system in the same network. I also tried disabling the firewall and system antivirus but it did not help.

@braginini 

let me try these and get back to you with an update.

**Comment by MANKUD** [comment]
> additionally to what @mlsmaycon asked, @MANKUD could you please run these commands?
> 
> `telnet apitest.wiretrustee.com 33073` `telnet apitest.wiretrustee.com 33071`
> 
> `telnet apitest.wiretrustee.com 80` `telnet apitest.wiretrustee.com 443`
> 
> What is the output?

telnet apitest.wiretrustee.com 33073

![image](https://user-images.githubusercontent.com/83474708/141643899-a51dd5aa-d06e-4f23-a54f-740b6fe8973a.png)

telnet apitest.wiretrustee.com 33071

![image](https://user-images.githubusercontent.com/83474708/141643902-5ed89dff-1d6a-4edf-b850-b14746f5bcc4.png)

telnet apitest.wiretrustee.com 80

![image](https://user-images.githubusercontent.com/83474708/141643908-784c8b99-32d4-41d0-a1ad-5eda64da2276.png)

telnet apitest.wiretrustee.com 443

![image](https://user-images.githubusercontent.com/83474708/141643911-a3692197-bf96-4a3c-b143-f728df924ad2.png)

**Comment by MANKUD** [comment]
@braginini @mlsmaycon 

I see that wiretrustee works without wireguard installed on the windows machine how does it work without wireguard running on the machine it's built over wireguard right?

**Comment by mlsmaycon** [comment]
> @braginini @mlsmaycon
> 
> I see that wiretrustee works without wireguard installed on the windows machine how does it work without wireguard running on the machine it's built over wireguard right?
> 
> I also could not find any wireguard tunnel created on windows not sure how it's working.

Yes, we are using wireguard-go package which is an official package from Wireguard. The interface is created after we connect to Management and Signal services, that is why you are unable to see such an interface.

**Comment by MANKUD** [comment]
@mlsmaycon thank you for the info I think this can me marked as resolved now.
