### ISSUE TITLE
RHEL repo server SSL certificate expired

### ISSUE THREAD

**Issue by gerwim** [wiretrustee/wiretrustee#172]
The SSL certificate expired yesterday (https://pkgs.wiretrustee.com/yum/):

```
Errors during downloading metadata for repository 'Wiretrustee':
  - Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://pkgs.wiretrustee.com/yum/repodata/repomd.xml [SSL certificate problem: certificate has expired]
```

<img width="843" alt="image" src="https://user-images.githubusercontent.com/1841721/147405407-b775701f-5bca-49e1-8ba2-e714c8bbca0b.png">

**Comment by mlsmaycon** [comment]
Thank you @gerwim , sorry you faced this issue. There was a bug with certbot configuration that is now fixed.
