### ISSUE TITLE
Extend client to support peer changes distribution

### ISSUE THREAD

**Issue by braginini** [wiretrustee/wiretrustee#19]
When a new peer is added other peers have to be notified of a newcomer

**Comment by casonadams** [comment]
Any thoughts around making the add peer have a ttl?

**Comment by braginini** [comment]
@casonadams what exactly do you mean? 
Something like this?
Adding peer let's say for a month (TTL = 1 month) and then it is removed automatically.

**Comment by casonadams** [comment]
Yeah in my use case I was thinking, I want to add a peer to do a file share, but have that peer be removed after a given TTL say 1 hour.  I want the TTL to be flexible too so I could have it set at 1 month or 1 minute.

**Comment by braginini** [comment]
Got you @casonadams 
It is a good feature and we will have it implemented.
Since all the peer management will be handled by the management system we will add it there.
You'd be able to control the list of peers and their TTLs through the centralized dashboard.
