### ISSUE TITLE
Detection of wireguard kernel module is broken for non amd64 architectures

### ISSUE THREAD

**Issue by stv0g** [wiretrustee/wiretrustee#201]
The current code taken from go-modprobe is pretty broken for any non-amd64 architectures:

https://github.com/paultag/go-modprobe/issues/4

I propose to rewrite the code to an look for the name in the `.modinfo` section.

**Comment by stv0g** [comment]
Related: https://github.com/wiretrustee/wiretrustee/pull/200

**Comment by stv0g** [comment]
Okay, next step. I fixed the parsing of kernel modules in https://github.com/paultag/go-modprobe/pull/5

However, now it fails as my system stored the modules in compressed LZMA format: https://github.com/paultag/go-modprobe/issues/6

**Comment by braginini** [comment]
Fixed
