### ISSUE TITLE
How are you going to do advance ACLs

### ISSUE THREAD

**Issue by ender049** [wiretrustee/wiretrustee#225]
I don't know if I understand this correctly.
wireturstee can get the wireguard encrypt data in the proxy
but in this way ,how to do the ACLs features ，such as port control

**Comment by mlsmaycon** [comment]
Hello, @ender049 our initial plan is to evolve the ACL, starting by allowing simple connection control between peers, then controlling specific ports and protocols. We are working on part of our connection layer that might allow us to do that without the proxy layer.
