### ISSUE TITLE
Alternatives to auth0 planed?

### ISSUE THREAD

**Issue by qupfer** [wiretrustee/wiretrustee#241]
hi, I understood that is good and practcable solution to outsource the login/auth part. 
But the wiretrustee overview image shows: "Identity provider e.g. auth0) that sounds its prepared for other ones.

I would realy love to have "self-hosted" one, maybe just a "http basic auth" one with manual added account(s). Did anyone start experiments in this direction?

thanks

**Comment by braginini** [comment]
Hey @qupfer 
Check this issue. We are considering some options :)
https://github.com/wiretrustee/wiretrustee-dashboard/issues/9
