### ISSUE TITLE
using the Self-hosting Guide without success

### ISSUE THREAD

**Issue by chmis8000** [wiretrustee/wiretrustee#244]
1:management.json:
![management json](https://user-images.githubusercontent.com/19686229/155884822-6d684879-462a-40fe-aa23-3bbb3d906c41.png)

2:docker-compose.yml:
![2022-02-27_214029](https://user-images.githubusercontent.com/19686229/155884766-dd0d7b1e-dcea-46e5-bda3-de73af10c07d.png)

3:[Coturn_log.txt](https://github.com/wiretrustee/wiretrustee/files/8148437/Coturn_log.txt)

4:https://github.com/wiretrustee/wiretrustee/blob/main/docs/self-hosting.md
vs
[README.md](https://github.com/wiretrustee/wiretrustee#readme) start with ""Running Dashboard, Management, Signal and Coturn"
The descriptions are inconsistent.

In addition to modifying setup.env, what else do I need to modify?
Can the documentation be improved? Thank you.

**Comment by Neptunespace** [comment]
Same here

**Comment by mlsmaycon** [comment]
Hello @chmis8000 @Neptunespace, sorry to hear that you are facing issues. I will review the guide and update it according to the latest changes.

**Comment by mlsmaycon** [comment]
Hello @chmis8000 and @Neptunespace,

We've updated the documentation and templates to reflect the latest changes and to offer a better support for turn configuration as well.

**Comment by chmis8000** [comment]
@mlsmaycon  it's not ok, signal,management,dashboard no error,coturn has many errors.
Change from centos8 system to ubuntu20.4 system/centos7.6.
![a](https://user-images.githubusercontent.com/19686229/158062291-8617794e-00a5-48fd-ac9d-dcc3314555c4.png)
![b](https://user-images.githubusercontent.com/19686229/158062338-2adff076-2318-46e5-a16b-2a0091f63b2c.png)
![c](https://user-images.githubusercontent.com/19686229/158062347-5b5e36eb-aac6-4f3a-baae-cc5589c9464f.png)
[error.txt](https://github.com/wiretrustee/wiretrustee/files/8239776/error.txt)

**Comment by mlsmaycon** [comment]
hello @chmis8000 most of the errors and warnings from Coturn are caused by default configuration settings. These are ok to ignore as they don't affect Coturn's functionality. 

The only settings that can be improved from our end are the certificate files path, that we can comment them out or point to the same files used by dashboard and management. Let me evaluate if they will work as expected or if we need further changes for that.

**Comment by chmis8000** [comment]
Do these errors of coturn not affect the use?
Is it the cause of auth0.com misconfiguration, now the error is:
Oops... Service not found: https://vpn.xxapp.cc
![dashboard](https://user-images.githubusercontent.com/19686229/158504488-5e9efe58-3183-4c0a-ae72-a57059a33cd8.png)

**Comment by chmis8000** [comment]
@mlsmaycon  
The "Oops... Service not found" problem has been solved
The reason is that the URL written by WIRETRUSTEE_AUTH0_AUDIENCE did not add / at the end.
I suggest you strengthen the documentation or improve the automatic judgment of the program.

But,However, the client cannot connect, the record in client.log file is: 
time="2022-03-17T13:44:42+08:00" level=error msg="failed to connect to service CLI interface context deadline exceeded".
Please take a look, what might be the problem?

**Comment by chmis8000** [comment]
I know the reason, I will open another post

**Comment by brandonros** [comment]
What is the reason?
