### ISSUE TITLE
Offline peers status 

### ISSUE THREAD

**Issue by cevinov** [wiretrustee/wiretrustee#265]
Hello sir,

I have a problem, after do run this command :
sudo wiretrustee up --setup-key<setup-key>. 

It automatically goes to offline status sir. How do i connect it ?.
Thanks.

Footage :
https://screenrec.com/share/ky16G5NM4g

**Comment by braginini** [comment]
Hi @cevinov 
Could you please tell me if you are using a self-hosted version or a managed one?

Could you please provide me with the contents of /var/log/wiretrustee/client.log?

Thank you!
You could also join our slack channel - should be faster communication-wise :)
https://join.slack.com/t/wiretrustee/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A

**Comment by cevinov** [comment]
> Hi @cevinov Could you please tell me if you are using a self-hosted version or a managed one?
> 
> Could you please provide me with the contents of /var/log/wiretrustee/client.log?
> 
> Thank you! You could also join our slack channel - should be faster communication-wise :) https://join.slack.com/t/wiretrustee/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A

Hello sir, thanks for the replies 

Here sir the log capture :
https://shrib.com/#BlackRhinoceros_YeKDW5

And im use the managed one version sir.

**Comment by braginini** [comment]
Closing the issue since it was resolved (after having a conversation with @cevinov in slack)
