### ISSUE TITLE
Try using connection candidates with wg before starting a proxy

### ISSUE THREAD

**Issue by stv0g** [wiretrustee/wiretrustee#33]
Currently, all Wireguard data is passed through the Wireguard proxy even though the connection candidates could be directly passed as peers to Wireguard. I think we only really need the proxy if a TCP TURN relay is used.

**Comment by braginini** [comment]
Thanks, @stv0g for the suggestion. 
It is generally a good idea to avoid using a local proxy for the Wg traffic, however, in our case it won't be a quick change.
Let me explain why.
1. We allow each peer to have multiple connections simulteniously.
2. We use plain pion/ice that has a hole punching logic embedded and handled by the framework. And it is always a new random UDP port.

So, we would always need to update the Wireguard listen port with a new port (from #2), this will interrupt other connections (#1) and the logic becomes quite complex.

We had an idea of taking control of a socket used by pion/ice and completely getting rid of a local proxy. We will be looking into that. 
For now, what we have implemented so far was the quickest (implementation-wise) and quite a good solution.

We will be also posting some benchmarks Pure Wireguard vs Wiretrustee.

**Comment by stv0g** [comment]
Hi @braginini 

thanks for the detailed explanation.

> So, as I understood you correctly, we would always need to update the Wireguard listen port with a new port (from #2), this will interrupt other connections (#1) and the logic becomes quite complex.

I agree. Maybe `AgentConfig.PortMin` and `AgentConfig.PortMax` could be used to restrict pion/ice to a single port which is used as Wireguards ListenPort?
pion/ice will probably fail as the port is already bound by Wireguard.
So Wireguard would need to be stopped during the connectivity checks and hole punching.

Indeed not a trivial change.

I thought about using iptables/netfilter with a redirect rule pointing to the chosen candidate pair.
But that wouldnt be portable :/

> We will be also posting some benchmarks Pure Wireguard vs Wiretrustee.

I would be very much interested in that!
