### ISSUE TITLE
Wireguard interface not up

### ISSUE THREAD

**Issue by xiya233** [wiretrustee/wiretrustee#45]
Hello everyone

I have a 5.10 kernel:

`uname -a`

`Linux debian-1cpu-1gb-sg-sin1 5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04) x86_64 GNU/Linux`

The wireguard kernel module has been loaded:
```
modprobe wireguard
lsmod | grep wireguard
```
```
wireguard              94208  0
libchacha20poly1305    16384  1 wireguard
ip6_udp_tunnel         16384  1 wireguard
udp_tunnel             20480  1 wireguard
libblake2s             16384  1 wireguard
curve25519_x86_64      49152  1 wireguard
libcurve25519_generic    49152  2 curve25519_x86_64,wireguard
```

After starting wiretrustee, there is no wiretrustee0 interface:

`systemctl status wiretrustee.service`

```
● wiretrustee.service - Wiretrustee Service
   Loaded: loaded (/lib/systemd/system/wiretrustee.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-07-05 14:41:31 UTC; 6min ago
 Main PID: 799 (wiretrustee)
    Tasks: 3 (limit: 1135)
   Memory: 6.7M
   CGroup: /system.slice/wiretrustee.service
           └─799 /usr/local/bin/wiretrustee up --config /etc/wiretrustee/config.json --log-level debug
```
`ip a`

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 46:d1:1a:9d:07:2e brd ff:ff:ff:ff:ff:ff
    inet xxx.xxx.xxx.xxx/22 brd xxx.xxx.xxx.xxx scope global dynamic eth0
       valid_lft 85710sec preferred_lft 85710sec
    inet6 fe80::44d1:1aff:fe9d:72e/64 scope link 
       valid_lft forever preferred_lft forever
```

What did i do wrong? Any suggestions, thanks

**Comment by braginini** [comment]
Hey,
Did you call `wiretrustee init` command?

And could you please provide the content of `/etc/wiretrustee/config.json` ? Please omit the private key.

**Comment by xiya233** [comment]
> Hey,
> Did you call `wiretrustee init` command?
> 
> And could you please provide the contents of `/etc/wiretrustee/config.json` ? Please omit the private key.

Sorry, it's my problem.

My firewall blocks the wiretrustee port

Your project is great!

**Comment by braginini** [comment]
I'm glad to hear that the problem has been solved
@xiya233 

Could you please which port was blocked by your firewall? Signal service port?

**Comment by xiya233** [comment]
@braginini 

Yes, there may be other ports that are also blocked.

I configure the firewall to allow all traffic to connect:

```
firewall-cmd --set-default-zone=trusted
firewall-cmd --reload
```

**Comment by braginini** [comment]
Alright, thank you.
Just opening signal port should be enough.
