### ISSUE TITLE
Error while connecting peer

### ISSUE THREAD

**Issue by bharathmsd7** [wiretrustee/wiretrustee#48]
Trying to connect peer using cmd
`sudo wiretrustee add-peer --allowedIPs 10.30.30.2/32 --key '<PEER2 PUBLIC KEY>'`

ERROR :
received a new message from Peer [fingerprint: peer1 publickey]"
error while handling message of Peer [key: <peer1 publickey>] error: [wrongly addressed message <peer1 publickey>]

**Comment by braginini** [comment]
Hey, could you please provide the contents of /etc/wiretrustee/config.json of both peers?

**Important!** Please remove private keys from the config.json before pasting the contents.

Thank you.

**Comment by bharathmsd7** [comment]
Peer 1 : 
{"PrivateKey":"privatekey","Peers":[{"WgPubKey":"publickey","WgAllowedIps":"10.30.30.2/32"}],"StunTurnURLs":[{"Scheme":1,"Host":"stun.wiretrustee.com","Port":3468,"Username":"","Password":"","Proto":1},{"Scheme":1,"Host":"stun.l.google.com","Port":19302,"Username":"","Password":"","Proto":1},{"Scheme":3,"Host":"stun.wiretrustee.com","Port":3468,"Username":"username1","Password":"password1","Proto":1}],"SignalAddr":"signal.wiretrustee.com:10000","WgAddr":"10.30.30.1/24","WgIface":"wiretrustee0","IFaceBlackList":null}

Peer 2 :
{"PrivateKey":"privatekey","Peers":null,"StunTurnURLs":[{"Scheme":1,"Host":"stun.wiretrustee.com","Port":3468,"Username":"","Password":"","Proto":1},{"Scheme":1,"Host":"stun.l.google.com","Port":19302,"Username":"","Password":"","Proto":1},{"Scheme":3,"Host":"stun.wiretrustee.com","Port":3468,"Username":"username1","Password":"password1","Proto":1}],"SignalAddr":"signal.wiretrustee.com:10000","WgAddr":"10.30.30.2/24","WgIface":"wiretrustee0","IFaceBlackList":null}

**Comment by braginini** [comment]
Thanks.

It seems like you haven't run on the the Peer 2
`sudo wiretrustee add-peer --allowedIPs 10.30.30.1/32 --key '<PEER1 PUBLIC KEY>'`

This is required in order Wireguard on Peer 2 accept requests from the Peer 1

P.S. we plan to release a peer management system soon so these kind of issues will be obsolete.


Let me know if it helped!

**Comment by bharathmsd7** [comment]
That helped me man, I am new to this tool. 
Thanks for the help.
