### ISSUE TITLE
Release 0.1.0 beta

### ISSUE THREAD

**Issue by braginini** [wiretrustee/wiretrustee#87]
- [x] Documentation
- [x] Explanatory videos
- [x] TURN auth
- [x] TURN auto cert
- [x] UI Dashboard
  - [x] Auth0 sign-up/login
  - [x] Peers view (list, delete, disable)
  - [x] Setup Keys view (list, delete disable)
  - [x] Add Peer view (getting started)
- [x] UI Dashboard Build
- [x] Management HTTP API
- [x] Management gRPC API
- [x] Client sync with Management gRPC
- [x] extract Auth0 creds

**Comment by KlavsKlavsen** [comment]
Shouldn't this task be closed - since 0.1.0 has been released? :)

**Comment by braginini** [comment]
A very good idea @KlavsKlavsen 😃
